version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  main-app:
    build:
      context: ./main-app
      dockerfile: Dockerfile
    environment:
      PAYMENT_BASE_URL: http://payment-service:8081
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - payment-service
      - redis
