create table if not exists items
(
    id          bigint generated by default as identity primary key,
    title       varchar(128) not null unique,
    description varchar(2048),
    img_path    varchar(256),
    price       bigint       not null
);

create table if not exists cart_items
(
    id      bigint generated by default as identity primary key,
    item_id bigint not null,
    user_id bigint not null default 1,
    count   int    not null,
    constraint uq_cart_items_user_item unique (user_id, item_id),
    constraint fk_cart_items_items foreign key (item_id) references items (id) on delete cascade
);

create table if not exists orders
(
    id      bigint generated by default as identity primary key,
    user_id bigint not null default 1
);

create table if not exists order_items
(
    id       bigint generated by default as identity primary key,
    order_id bigint not null,
    item_id  bigint not null,
    count    int    not null,
    constraint fk_order_items_orders foreign key (order_id) references orders (id) on delete cascade,
    constraint fk_order_items_items foreign key (item_id) references items (id)
);

create table if not exists users
(
    id       bigint generated by default as identity primary key,
    username varchar(64)  not null unique,
    password varchar(255) not null,
    role     varchar(64)  not null,
    enabled  boolean      not null default true
);
